#ifndef BaseBase_hpp
#define BaseBase_hpp

#include "Allocator.hpp"
#include "AnimatedSprite.hpp"
#include "Animation.hpp"
#include "Application.hpp"
#include "Array.hpp"
#include "BitFlag.hpp"
#include "Camera.hpp"
#include "Collider.hpp"
#include "Component.hpp"
#include "FileIO.hpp"
#include "GameObject.hpp"
#include "Json.hpp"
#include "Math.hpp"
#include "Scene.hpp"
#include "Schedule.hpp"
#include "SDL.hpp"
#include "SDLInput.hpp"
#include "SDLMixer.h"
#include "SDLWindow.hpp"
#include "ShaderProgram.hpp"
#include "Sprite.hpp"
#include "Storage.hpp"
#include "String.hpp"
#include "TextureStorage.hpp"
#include "Time.hpp"
#include "types.hpp"
#include "Vector.hpp"
#include "Physics.hpp"

#endif